package Car;

public enum GearboxType {
    MANUAL,
    AUTOMATIC,
    CONTINUOUSLY_VARIABLE_TRANSMISSION,
    DUAL_CLUTCH_TRANSMISSION,
    SEQUENTIAL,
    DIRECT_SHIFT_GEARBOX,
    HYDRAULIC_TORQUE_CONVERTER,
    EPICYCLIC_GEARBOX,
    CONSTANTLY_VARIABLE_TRANSMISSION,
    PRESELECTOR_GEARBOX
}